export type Sample = {
  id: string;
  label: string;
  flag: string;
  note: string;
};

// The sample gallery: fake invoices bundled so visitors never need to upload
// anything real. Files live in /public/samples, generated by the extractor's
// samples/generate.py.
export const SAMPLES: Sample[] = [
  { id: "01_de_simple", label: "Schreiner & Sohn", flag: "🇩🇪", note: "Standard 19% invoice" },
  { id: "02_de_7pct", label: "Buchhandlung Lesezeit", flag: "🇩🇪", note: "Books, 7% reduced rate" },
  { id: "03_de_mixed_rates", label: "Gasthaus zur Linde", flag: "🇩🇪", note: "Mixed 7% + 19% (catering)" },
  { id: "04_de_discount", label: "BüroTech Handels", flag: "🇩🇪", note: "With a discount line" },
  { id: "05_de_kleinunternehmer", label: "Fotografie Bergmann", flag: "🇩🇪", note: "Kleinunternehmer, 0% VAT (§19)" },
  { id: "06_de_gutschrift", label: "BüroTech Gutschrift", flag: "🇩🇪", note: "Credit note, negative amounts" },
  { id: "07_de_no_iban", label: "Nachhilfe Institut Klug", flag: "🇩🇪", note: "No IBAN (SEPA direct debit)" },
  { id: "08_at_20pct", label: "Alpenblick Software", flag: "🇦🇹", note: "Austrian, 20% + ATU VAT id" },
  { id: "09_en_nl_vat", label: "Windmill Digital B.V.", flag: "🇳🇱", note: "English, Dutch 21% VAT" },
  { id: "10_en_uk", label: "Thames Analytics Ltd", flag: "🇬🇧", note: "English, UK 20% VAT" },
  { id: "11_en_usd_novat", label: "Prairie Cloud Services", flag: "🇺🇸", note: "USD, reverse charge (no VAT)" },
  { id: "12_de_thousands", label: "Stahlbau Krämer AG", flag: "🇩🇪", note: "Large amounts, 1.234,56 format" },
  { id: "13_de_freelancer", label: "Jonas Winter IT", flag: "🇩🇪", note: "Freelancer, hourly billing" },
  { id: "14_en_fractions", label: "Beacon Legal Translations", flag: "🇧🇪", note: "Fractional quantities" },
  { id: "15_de_utility", label: "Stadtwerke Sonnenfeld", flag: "🇩🇪", note: "Utility bill, small unit prices" },
  { id: "16_en_mixed", label: "Fjord Consulting ApS", flag: "🇩🇰", note: "English, Danish 25% VAT" },
];
